name: Build and publish to PyPI

on:
  release: 
    types: [published]

jobs:
  PyPI-Release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: action/checkout@v3

    - name: Build Package
      run: 
        python -m pip install --upgrade pip build
        python -m build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TESTPYPI_API_TOKEN }}
        respository_url: http://test.pypi.org/legacy/